# Generated by Django 3.0.3 on 2020-03-13 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='nome')),
                ('sigla', models.CharField(max_length=50, verbose_name='sigla')),
                ('data_icinio', models.DateField(verbose_name='Data de Inicio')),
                ('realizador', models.CharField(max_length=50, verbose_name='realizador')),
                ('descricao', models.TextField()),
            ],
        ),
    ]
